language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script: chmod +x send_test_to_firebase.sh
script: ./send_test_to_firebase.sh